>>> radius = float(input("Enter the radius of the circle: "))
Enter the radius of the circle: 7
>>> area = 3.14 * radius ** 2
>>> print(f"The area of the circle with radius {radius} is: {area}")
The area of the circle with radius 7.0 is: 153.86
>>> radius = float(input("Enter the radius of the circle: "))
Enter the radius of the circle: 6.31
>>> area = 3.14 * radius * 2
>>> print(f"The area of the circle with radius {radius} is: {area}")
The area of the circle with radius 6.31 is: 39.626799999999996
>>> radius = float(input("Enter the radius of the circle: "))
Enter the radius of the circle: 14.96
>>> area = 3.14 * radius * 2
>>> print(f"The area of the circle with radius {radius} is: {area}")
The area of the circle with radius 14.96 is: 93.9488
