>>> width = int(input("Enter the width: "))
Enter the width: 9
>>> height = int(input("Enter the height: "))
Enter the height: 7
>>> depth = int(input("Enter the depth: "))
Enter the depth: 5
>>> volume = width * height * depth
>>> print(f"The volume of the cuboid is", volume, "cubic units")
The volume of the cuboid is 315 cubic units
>>> width = int(input("Enter the width: "))
Enter the width: 7
>>> height = int(input("Enter the height: "))
Enter the height: 4
>>> depth = int(input("Enter the depth: "))
Enter the depth: 3
>>> volume = width * height * depth
>>> print(f"The volume of the cuboid is", volume, "cubic units")
The volume of the cuboid is 84 cubic units
>>> width = int(input("Enter the width: "))
Enter the width: 6
>>> height = int(input("Enter the height: "))
Enter the height: 6
>>> depth = int(input("Enter the depth: "))
Enter the depth: 6
>>> volume = width * height * depth
>>> print(f"The volume of the cuboid is", volume, "cubic units")
The volume of the cuboid is 216 cubic units
