>>> width = int(input("Enter with width:"))
Enter with width:4
>>> height = int(input("Enter with height:"))
Enter with height:11
>>> area = width * height
>>> print ("The area is", area, "square units.")
The area is 44 square units.
>>> width = int(input("Enter with width:"))
Enter with width:15
>>> height = int(input("Enter with height:"))
Enter with height:8
>>> area = width * height
>>> print ("The area is", area, "square units.")
The area is 120 square units.
>>> width = int(input("Enter with width:"))
Enter with width:8
>>> height = int(input("Enter with height:"))
Enter with height:8
>>> area = width * height
>>> print ("The area is", area, "square units.")
The area is 64 square units.
>>>
