>>> base = int(input("Enter with base:"))
Enter with base:6
>>> height = int(input("Enter with height:"))
Enter with height:9
>>> area = 0.5 * base * height
>>> print(f"The area of the triangle with base {base} and height {height} is: {area}")
The area of the triangle with base 6 and height 9 is: 27.0
>>> base = float(input("Enter the base of the triangle: "))
Enter the base of the triangle: 4
>>> height = float(input("Enter the height of the triangle: "))
Enter the height of the triangle: 8
>>> area = 0.5 * base * height
>>> print(f"The area of the triangle with base {base} and height {height} is: {area}")
The area of the triangle with base 4.0 and height 8.0 is: 16.0
>>> base = float(input("Enter the base of the triangle: "))
Enter the base of the triangle: 9
>>> height = float(input("Enter the height of the triangle: "))
Enter the height of the triangle: 9
>>> area = 0.5 * base * height
>>> print(f"The area of the triangle with base {base} and height {height} is: {area}")
The area of the triangle with base 9.0 and height 9.0 is: 40.5
>>>
